<a href="https://colab.research.google.com/github/bhaskart488/islp/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [3]:
# print?

# provide docstring
# Docstring:
# print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

# Prints the values to a stream, or to sys.stdout by default.
# Optional keyword arguments:
# file:  a file-like object (stream); defaults to the current sys.stdout.
# sep:   string inserted between values, default a space.
# end:   string appended after the last value, default a newline.
# flush: whether to forcibly flush the stream.
# Type:      builtin_function_or_method

In [5]:
x = [3,4,5]
x

[3, 4, 5]

In [6]:
y = [7,8,9]
x + y

[3, 4, 5, 7, 8, 9]

Intro to Numerical Python

In [7]:
import numpy as np

In [8]:
x = np.array([3,4,5])
y = np.array([4,9,7])

x + y

array([ 7, 13, 12])

In [10]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim  # dimension of x

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x.shape

(2, 2)

`reshape() method`

In [14]:
x = np.array([1,2,3,4,5,6])
print('beginning x:', x)

beginning x: [1 2 3 4 5 6]


In [17]:
x_reshape = x.reshape((2,3))
print('reshaped x: \n', x_reshape)

reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [18]:
x_reshape[1,2] = 0
x_reshape

array([[1, 2, 3],
       [4, 5, 0]])

In [19]:
x

array([1, 2, 3, 4, 5, 0])

Modifying `x_reshape` also modified `x` as both occupy the same memory space.

In [20]:
my_tuple = (3,4,5)

# my_tuple[0] = 7


TypeError: 'tuple' object does not support item assignment